# Base image
FROM node:24

# Set the working directory in the container
WORKDIR /app

COPY ../package.json ../pnpm-lock.yaml ../pnpm-workspace.yaml ./

# Install app dependencies
RUN npm install -g pnpm@11.16.0

RUN pnpm install --frozen-lockfile
